#' Compute all shortest distance between origin and destination nodes.
#'
#' @param edgelist Object generated by \link{make_edgelist} function.
#' @param from A vector of one or more vertices from which distances are calculated (origin).
#' @param to A vector of one or more vertices (destination).
#' @param aggregate_aux Logical. If \code{TRUE}, the additional weight is summed along shortest paths.
#' @return Matrix of shortest distances.
#' @details \code{calc_network_distance()} recursively perform Dijkstra for each \code{from} nodes.
#'
#' Shortest path is always computed according to the main edge weights, corresponding to the 3rd column of \code{df} argument in \code{make_edgelist()} function.
#' If \code{aggregate_aux} argument is \code{TRUE}, the values returned are the sum of auxiliary weights along shortest paths.
#'
#' @export

calc_network_distance <- function(edgelist, from, to, aggregate_aux = FALSE, max_aux = Inf){
  
  if (any(is.na(from))) stop("NAs are not allowed in origin/destination nodes")
  if (any(is.na(to))) stop("NAs are not allowed in origin/destination nodes")
  
  from <- as.character(from)
  to <- as.character(to)
  
  allnodes <- c(from,to)
  
  if (sum(allnodes %in% edgelist$dict$ref)<length(allnodes)) stop("Some nodes are not in the edgelist")
  
  from_id <- edgelist$dict$id[match(from,edgelist$dict$ref)]
  to_id <- edgelist$dict$id[match(to,edgelist$dict$ref)]
  
  if (aggregate_aux & length(edgelist$attrib$aux) == 0) stop("network don't have additional weight")
  
  if (length(from) < length(to)){
    if (aggregate_aux){
      res <- cpppadd(
        edgelist$data[,1], 
        edgelist$data[,2], 
        edgelist$data[,3], 
        edgelist$attrib$aux, 
        edgelist$nbnode, 
        from_id, 
        to_id, 
        max_aux)
    } else{
      res <- cppdistmat(
        edgelist$data[,1], 
        edgelist$data[,2], 
        edgelist$data[,3], 
        edgelist$nbnode, 
        from_id, 
        to_id, 
        max_aux)
    }
  } else {
    if (aggregate_aux){
      res <- cpppadd(
        edgelist$data[,2],
        edgelist$data[,1], 
        edgelist$data[,3],
        edgelist$attrib$aux, 
        edgelist$nbnode, 
        to_id, 
        from_id,
        max_aux)
    } else{
      res <- cppdistmat(
        edgelist$data[,2], 
        edgelist$data[,1], 
        edgelist$data[,3], 
        edgelist$nbnode, 
        to_id, 
        from_id, 
        max_aux)
    }
  }
  
  if (!(length(from)< length(to))) res<-t(res)
  
  rownames(res)<-from
  colnames(res)<-to
  return(res)
}
