# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppdistmat <- function(gfrom, gto, gw, nb, dep, arr, max_aux) {
    .Call(`_patchmax_cppdistmat`, gfrom, gto, gw, nb, dep, arr, max_aux)
}

cpppadd <- function(gfrom, gto, gw, gadd, nb, dep, arr, max_aux) {
    .Call(`_patchmax_cpppadd`, gfrom, gto, gw, gadd, nb, dep, arr, max_aux)
}

